spring:
  application:
    name: cart-service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/cart?ssl=false
server:
  port: 9099
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/


