spring:
  application:
    name: CART-SERVICE
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/cart?ssl=false
  output:
    ansi:
      enabled: always
server:
  port: 9099
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: ServiceLog.log
  level:
    root: INFO
