spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/rating?ssl=false
server:
  port: 9096
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/